### ISSUE TITLE
add this module to nuxt modules website

### ISSUE THREAD

**Issue by blackinitial** [ivodolenc/nuxt-animejs#3]
hi @ivodolenc , can you add this module to nuxt module [website](https://modules.nuxtjs.org/) ?

**Comment by BibekStha** [comment]
@blackinitial has already created the issue on the nuxt module GitHub for this.
[https://github.com/nuxt/modules/issues/105](https://github.com/nuxt/modules/issues/105)

**Comment by blackinitial** [comment]
Yeah, but i think the maintainer is good to PR

**Comment by BibekStha** [comment]
I agree.

Is there documentation on what needs to be included in the PR for nuxt modules?

**Comment by ivodolenc** [comment]
Hi, thanks for your interest in this module/s, I appreciate your suggestion. I'm glad to see that someone finds this module/s useful and wants to share suggestions or support. That means a lot.

As for `PR`, I see that you have already added request to the official `nuxt/modules` repo so there is no need to add it twice 🤝 😉

Thanks again for that 👍

**Comment by blackinitial** [comment]
> Hi, thanks for your interest in this module/s, I appreciate your suggestion. I'm glad to see that someone finds this module/s useful and wants to share suggestions or support. That means a lot.
> 
> As for `PR`, I see that you have already added request to the official `nuxt/modules` repo so there is no need to add it twice 🤝 😉
> 
> Thanks again for that 👍

Usefull cause yesterday i find this module, thanks.

**Comment by ivodolenc** [comment]
Closing this as resolved since the module can be found on the [official](https://modules.nuxtjs.org/) site (`Libraries` → `animejs`).

**Comment by blackinitial** [comment]
Woah, thats great
Thanks...
