### ISSUE TITLE
Type script support for injection?

### ISSUE THREAD

**Issue by ortonomy** [ivodolenc/nuxt-animejs#4]
In nuxt with typescript, you need to do some pretty complicated declarations in the plugin to make it work in different areas of the app with nuxt as per the cookbook here:

https://typescript.nuxtjs.org/cookbook/plugins/

![Selection_001](https://user-images.githubusercontent.com/6688676/132978946-bef931fd-27cc-465c-97c5-69d0c0bc52e6.png)

How can I get that support with this module?

(and yes, I've already set up the module in `buildModules` in `nuxt.config.js`

**Comment by ivodolenc** [comment]
Hi and thanks for your interest in this module.

I haven't tested this module in `typescript` setup so I'm not sure if it works well in that environment. However, you can import `anime.js` manually and use it as recommended by official guidelines.

**Comment by ortonomy** [comment]
Hi! Thanks for responding. Going to leave this here for anyone else in the future:

To use **animejs** with **nuxtjs** you should follow the 'plugin' recipe set out in the nuxtjs cookbook here: https://typescript.nuxtjs.org/cookbook/plugins/

1. Install _animejs_
2. Install _@types/animejs (dev)_
3. Setup _this.$anime_ using the plugin system and extend the Vulcan interface as per the cookbook. 

All done. You lose the the custom directive, but it's not big loss.
