### ISSUE TITLE
Not able to implement with Nuxt3

### ISSUE THREAD

**Issue by pareshpandit** [ivodolenc/nuxt-animejs#7]
I tried various permutations and combinations, but it seems that Nuxt3 is not yet playing well with nuxt-animejs. Could you kindly look into this, or guide a noob? 

The following error crops up, when following the existing instructions: 
```
[nuxt] [request error] Cannot read properties of undefined (reading 'directive')
  at $id_e16a0966 (./.nuxt/dist/server/server.mjs:2953:31)  
  at async __instantiateModule__ (./.nuxt/dist/server/server.mjs:5306:3)
```

**Comment by ivodolenc** [comment]
Hi, thanks for your interest in this module. 

Currently the module is not compatible with Nuxt 3 version (v3 is a breaking change). 

For now, you can manually import `animejs` into your Nuxt 3 project.
